### ISSUE TITLE
The logo covers part of the QR Code

### ISSUE THREAD

**Issue by LivioGama** [gcoro/react-qrcode-logo#7]
QR Code become unreadable when using a logo...

**Comment by gcoro** [comment]
The error correction is used to keep the QR Code readable even if a part of it is covered... 
Try setting a higher error correction level or making the logo smaller through the component props

**Comment by LivioGama** [comment]
This is what I did, but I don't thing it's normal to randomly check which size is going to make it work.

**Comment by gcoro** [comment]
Hmm but I think it would be a limitation to now allow to set every logo size within this library, because readability doesn't only depend on size (for example one could set logo size as big as the whole QR Code and reduce opacity so it still can be readable). Do you have any suggestions? 

Maybe you can try to limit the logo dimensions that the user can set in your code, or implement a check that reads the resulting QR Code and if it can't decode it, shows the user a warning

**Comment by LivioGama** [comment]
I limited the size to something like 20% of the width to fix the use case where I had the problem, let's hope that it will be good for everything!
